server:
  port: 9000
spring:
  application:
    name: timesheet-gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/

zuul:
   prefix: /project
   routes:
     timesheet:
       path: /timesheet/**
       serviceId: eureka-client-timesheet
       strip-prefix: false